User.create!([
  {email: "user@test.com", encrypted_password: "$2a$11$SOEpVQBPEkzzCOqXLRPtxO.PEu.jpGTXXxydDI33pl2j/B9VbjUaW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-05-13 21:53:59", last_sign_in_at: "2016-05-12 01:50:21", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "4084325748", location: "13850 Saratoga Ave, Saratoga, CA", bio: "Hi! My name is John Doe. I live in the South Bay Area. I just moved into the area, and I am looking for a regular gaming group! I generally enjoy American games, but I am open to anything.", admin: false, first_name: "John", last_name: "Doe"}
])
Boardgame.create!([
  {name: "Blood Rage", developer: "Eric Lang"},
  {name: "Agricola", developer: "Uwe Rosenberg"},
  {name: "Pandemic", developer: "Matt Leacock"},
  {name: "Dominion", developer: "Donald X. Vaccarino"},
  {name: "The Resistance", developer: "Don Eskridge"},
  {name: "Carcassonne", developer: "Klaus-Jürgen Wrede"},
  {name: "For Sale", developer: "Stefan Dorra"},
  {name: "Saint Petersburg", developer: "Bernd Brunnhofer"},
  {name: "Space Hulk: Death Angel", developer: "Corey Konieczka"},
  {name: "BANG!", developer: "Emiliano Sciarra"}
])
CategorizedBoardgame.create!([
  {category_id: 2, boardgame_id: 2},
  {category_id: 4, boardgame_id: 2},
  {category_id: 5, boardgame_id: 2},
  {category_id: 6, boardgame_id: 2},
  {category_id: 7, boardgame_id: 2},
  {category_id: 2, boardgame_id: 4},
  {category_id: 11, boardgame_id: 4},
  {category_id: 8, boardgame_id: 4},
  {category_id: 12, boardgame_id: 4},
  {category_id: 13, boardgame_id: 4},
  {category_id: 7, boardgame_id: 4},
  {category_id: 6, boardgame_id: 5},
  {category_id: 14, boardgame_id: 5},
  {category_id: 8, boardgame_id: 5},
  {category_id: 15, boardgame_id: 6},
  {category_id: 16, boardgame_id: 6},
  {category_id: 17, boardgame_id: 6},
  {category_id: 4, boardgame_id: 7},
  {category_id: 18, boardgame_id: 7},
  {category_id: 8, boardgame_id: 8},
  {category_id: 19, boardgame_id: 8},
  {category_id: 6, boardgame_id: 9},
  {category_id: 13, boardgame_id: 9},
  {category_id: 10, boardgame_id: 3},
  {category_id: 9, boardgame_id: 3},
  {category_id: 6, boardgame_id: 3},
  {category_id: 8, boardgame_id: 3},
  {category_id: 20, boardgame_id: 10},
  {category_id: 11, boardgame_id: 10},
  {category_id: 21, boardgame_id: 10},
  {category_id: 7, boardgame_id: 10},
  {category_id: 8, boardgame_id: 10},
  {category_id: 7, boardgame_id: 11},
  {category_id: 23, boardgame_id: 11},
  {category_id: 22, boardgame_id: 11},
  {category_id: 8, boardgame_id: 11},
  {category_id: 15, boardgame_id: 11}
])
Category.create!([
  {mechanism: "Action point allowance system"},
  {mechanism: "Area control"},
  {mechanism: "Area movement"},
  {mechanism: "Card drafting"},
  {mechanism: "Variable player powers"},
  {mechanism: "Hand management"},
  {mechanism: "Worker placement"},
  {mechanism: "Area enclosure"},
  {mechanism: "Co-operative play"},
  {mechanism: "Point to point movement"},
  {mechanism: "Set collection"},
  {mechanism: "Deck building"},
  {mechanism: "Partnerships"},
  {mechanism: "Simultaneous action selection"},
  {mechanism: "Voting"},
  {mechanism: "Tile placement"},
  {mechanism: "Bidding"},
  {mechanism: "Action / movement programming"},
  {mechanism: "Dice rolling"},
  {mechanism: "Player elimination"},
  {mechanism: "Take that"}
])
Picture.create!([
  {user_id: 2, link: "http://orig04.deviantart.net/aded/f/2013/066/c/2/profile_picture_by_naivety_stock-d5x8lbn.jpg"},
  {user_id: 2, link: "http://orig03.deviantart.net/23a2/f/2010/352/f/7/headshotid_by_bokogreat_stock-d355xf3.jpg"}
])
