User.create!([
  {email: "henrique_sanna@gmail.com", encrypted_password: "$2a$11$Tj43bjyMb/ivh7eHlTGrgeexokmus9/TqvARDACVUT4wdESJQL9AK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-22 09:08:58", last_sign_in_at: "2016-06-22 09:08:58", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "9182231824", location: "Pomona, CA", bio: "Kinfolk mixtape everyday carry banh mi slow-carb sartorial, etsy post-ironic taxidermy humblebrag freegan umami paleo. Semiotics heirloom humblebrag, brunch four loko distillery yuccie small batch pour-over chambray. Kombucha gentrify try-hard asymmetrical. Crucifix scenester knausgaard letterpress, pitchfork PBR&B farm-to-table yuccie cold-pressed freegan salvia mustache pug. Hella biodiesel keytar hoodie distillery, polaroid PBR&B ennui vegan put a bird on it single-origin coffee trust fund. Whatever PBR&B lomo hoodie, 8-bit photo booth butcher. Pug hella hoodie, tattooed salvia kinfolk helvetica semiotics.", admin: false, first_name: "Henrique", last_name: "Sanna", profile_picture: 31, password: "password"},
  {email: "tasso_susvid@gmail.com", encrypted_password: "$2a$11$7ljRGC56OMHie8hLWEpc3.kpTBK1PD4V9Nbwzv4BgEBWoqZ1wUTwm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-06-22 21:00:05", last_sign_in_at: "2016-06-22 19:23:48", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "9491872319", location: "Venice Beach, CA", bio: "Locavore vero kickstarter, laborum tattooed cornhole kitsch before they sold out tofu stumptown cliche squid leggings helvetica. Chartreuse quinoa wayfarers waistcoat salvia, flexitarian iPhone proident squid nesciunt in kitsch. Twee lo-fi man bun, migas celiac cliche asymmetrical cardigan velit stumptown. Enim aute roof party, nisi sint bitters ex shabby chic chambray labore do disrupt stumptown nulla. Eu consequat tempor 8-bit food truck. Hashtag taxidermy single-origin coffee, typewriter small batch nulla offal eu. Meh sriracha irure, consectetur deep v pickled officia.", admin: false, first_name: "Tasso", last_name: "Susvid", profile_picture: 36, password: "password"},
  {email: "louise_fejes@gmail.com", encrypted_password: "$2a$11$qBvKjSJu57QIK9kH./E/mORUJWoM.RwUwlHwMquLsjVNicHaXxgH2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-22 08:59:06", last_sign_in_at: "2016-06-22 08:59:06", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "3821992732", location: "San Francisco, CA", bio: "Tote bag tattooed pour-over artisan. Four loko everyday carry mixtape salvia, venmo flannel kinfolk tote bag vegan chillwave semiotics jean shorts art party leggings. Pop-up skateboard paleo microdosing, cardigan godard craft beer slow-carb meditation letterpress. Yr pug kickstarter, 3 wolf moon freegan green juice tilde meh chia heirloom chicharrones master cleanse. Pitchfork keffiyeh 8-bit irony. Paleo franzen banjo pork belly fanny pack, beard XOXO distillery post-ironic gentrify. Cray poutine forage chicharrones, franzen locavore health goth gentrify migas hammock crucifix normcore ramps YOLO freegan.", admin: false, first_name: "Louise", last_name: "Fejes", profile_picture: 28, password: "password"},
  {email: "evelyn_spillum@gmail.com", encrypted_password: "$2a$11$.WHDro17oivf/suZc84O7.kkSYPakHnoI8CjwyC7hwIf9PVNyEEiS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-22 09:20:19", last_sign_in_at: "2016-06-22 09:20:19", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "8281023947", location: "San Mateo, CA", bio: "Whatever salvia sint yuccie. Echo park narwhal ad intelligentsia. DIY VHS literally, kombucha man bun magna duis exercitation portland consequat. Artisan roof party ex, id small batch laboris vice deep v. Placeat accusamus plaid, mlkshk farm-to-table bicycle rights occupy narwhal distillery fap sustainable fugiat irure flexitarian. Sunt aliquip migas selfies kickstarter. Celiac austin tote bag polaroid narwhal ex shabby chic typewriter, franzen slow-carb direct trade reprehenderit man braid neutra biodiesel.", admin: false, first_name: "Evelyn", last_name: "Spillum", profile_picture: 37, password: "password"},
  {email: "caterina_acconcio@hotmail.com", encrypted_password: "$2a$11$fvbSQ2grF4msgnZKuGdks.SYh1TNIV.EUNKKNhrRqaxdlHezJEsd2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-22 09:05:29", last_sign_in_at: "2016-06-22 09:05:29", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "1983211324", location: "San Francisco, CA", bio: "Blue bottle freegan yuccie, cliche knausgaard flannel asymmetrical. Beard slow-carb ramps waistcoat. Gastropub put a bird on it iPhone jean shorts blue bottle. Pitchfork shoreditch kombucha offal, godard neutra drinking vinegar migas butcher etsy venmo squid cornhole 3 wolf moon four dollar toast. Swag gluten-free fixie authentic ramps trust fund. Vinyl hashtag mumblecore, wolf tilde intelligentsia tofu single-origin coffee seitan. Man braid hammock 90's, retro pickled direct trade photo booth pitchfork keffiyeh blog vice put a bird on it.", admin: false, first_name: "Caterina", last_name: "Acconcio", profile_picture: 30, password: "password"},
  {email: "admin@test.com", encrypted_password: "$2a$11$UsZtshjDHemB918DFtjrs.802udB8NO6UQRvScHmAU5AjgHWyYcGm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 86, current_sign_in_at: "2016-06-22 23:14:05", last_sign_in_at: "2016-06-22 21:18:00", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: nil, location: nil, bio: nil, admin: true, first_name: nil, last_name: nil, profile_picture: nil, password: "password"},
  {email: "gareth_gerver@gmail.com", encrypted_password: "$2a$11$bcnAiBWE3MtZ.onigBr2SujbXz8mHXPOAY7/yaogTlO/NA8Fzk.Wi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-06-22 18:50:58", last_sign_in_at: "2016-06-22 09:14:09", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "4152913940", location: "Saratoga, CA", bio: "Wayfarers selfies ad fixie mustache. Ea PBR&B meditation before they sold out deep v tote bag organic. Elit odio pabst, blue bottle pug deep v chillwave truffaut dolor selfies. Affogato salvia kinfolk irony kickstarter et, gochujang franzen. Retro quis sint pickled echo park kogi. Tousled deserunt biodiesel, art party occupy schlitz deep v selfies voluptate tote bag nulla. Butcher slow-carb wayfarers, officia squid flexitarian everyday carry.", admin: false, first_name: "Gareth", last_name: "Gerver", profile_picture: 54, password: "password"},
  {email: "willihard_andreasen@gmail.com", encrypted_password: "$2a$11$E3VIkBAd91gOHT/ehwGv6.qf7ab0p6Lj2RHEtPKQgC5LP96mE67AG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-06-22 19:01:15", last_sign_in_at: "2016-06-22 09:23:20", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "4921022938", location: "Vallejo, CA", bio: "Tofu cold-pressed tacos banh mi skateboard fixie. Austin lumbersexual quinoa small batch ugh twee 90's church-key. Forage VHS gluten-free, selvage four loko salvia street art selfies. Pour-over craft beer kickstarter distillery austin. Kogi waistcoat cliche skateboard gastropub, tacos hella whatever photo booth polaroid seitan. Chambray listicle blog occupy. Pinterest cardigan gentrify, normcore stumptown whatever squid kickstarter aesthetic pork belly try-hard kogi.", admin: false, first_name: "Willihard", last_name: "Andreasen", profile_picture: 57, password: "password"},
  {email: "samson_parri@gmail.com", encrypted_password: "$2a$11$lOYhAzgz.SeQIfthrKIQR.VKp5gQPDkqh0gzc0yw1HDZgaM2WOtmK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-06-22 19:09:23", last_sign_in_at: "2016-06-22 09:11:51", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "4082341928", location: "San Francisco, CA", bio: "Skateboard ennui letterpress gochujang next level. Twee pickled chambray polaroid, kitsch pop-up brooklyn gochujang cornhole gastropub listicle tacos readymade disrupt. Aesthetic neutra pickled leggings, street art occupy polaroid heirloom wolf typewriter art party. Humblebrag kombucha trust fund, vegan street art fingerstache tilde freegan four dollar toast mumblecore. Green juice art party meditation, salvia kitsch tote bag shoreditch freegan vice 90's tumblr scenester. Kitsch tofu semiotics, etsy actually trust fund taxidermy raw denim. Seitan humblebrag man bun letterpress.", admin: false, first_name: "Samson", last_name: "Parri", profile_picture: 32, password: "password"},
  {email: "jay_doe@yahoo.com", encrypted_password: "$2a$11$SOEpVQBPEkzzCOqXLRPtxO.PEu.jpGTXXxydDI33pl2j/B9VbjUaW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 119, current_sign_in_at: "2016-06-22 23:14:45", last_sign_in_at: "2016-06-22 23:08:22", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "4152173823", location: "San Jose, CA", bio: "Hi! My name is John Doe. I live in the South Bay Area. I just moved into the area, and I am looking for a regular gaming group! I generally enjoy American games with a lot of conflict, but I am open to any type of board game!", admin: false, first_name: "Jay", last_name: "Doe", profile_picture: 56, password: "password"},
  {email: "samuel_marley@gmail.com", encrypted_password: "$2a$11$BhIGXx1MpWmgcc2vPYeNCObVR8s3mnV2OOiZ.H4/8czffW/UJGWOK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-22 09:31:04", last_sign_in_at: "2016-06-22 09:31:04", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "3821923820", location: "Berkeley, CA", bio: "Health goth flexitarian beard tilde readymade. Tacos cronut brunch, kitsch dreamcatcher retro portland umami lomo. Stumptown cray bitters, YOLO authentic sartorial 3 wolf moon viral street art health goth next level XOXO gastropub brooklyn typewriter. Art party keffiyeh hoodie, twee banh mi tofu butcher single-origin coffee kickstarter. Intelligentsia DIY fanny pack shoreditch butcher taxidermy. Art party tattooed biodiesel, four dollar toast forage cray viral small batch salvia. Roof party keytar banh mi green juice, vinyl lumbersexual raw denim.", admin: false, first_name: "Samuel", last_name: "Marley", profile_picture: 45, password: "password"},
  {email: "krisztina_huerta@gmail.com", encrypted_password: "$2a$11$k38Xq7nMdyCWIsdR588Ivuf2kxJVQxKfXyf1l9yCQbX1h1BfUIQnG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-06-22 19:02:50", last_sign_in_at: "2016-06-22 09:28:22", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "2391428540", location: "Daly City, CA", bio: "Mumblecore godard neutra banjo literally banh mi squid, marfa man bun meh health goth vice drinking vinegar franzen gentrify. Vegan put a bird on it fashion axe sriracha, biodiesel intelligentsia pickled tote bag hoodie farm-to-table. Letterpress kogi messenger bag tote bag, drinking vinegar ethical organic etsy lomo actually. Post-ironic next level man bun, locavore green juice chartreuse meh ennui blog squid. +1 lumbersexual pour-over, aesthetic yuccie pop-up marfa actually pinterest poutine four dollar toast. Selvage meh bespoke freegan heirloom. Whatever pabst vegan biodiesel, venmo kinfolk food truck umami meggings farm-to-table portland.", admin: false, first_name: "Krisztina", last_name: "Huerta", profile_picture: 62, password: "password"},
  {email: "colton_thompsett@gmail.com", encrypted_password: "$2a$11$Wns71zNgy0pCJns5Vf5gLOoZbPzI0a/gJ0W62VKBGSjXMXX.UOrbq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-06-22 21:26:08", last_sign_in_at: "2016-06-22 09:34:24", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "9381024921", location: "Oakland, CA", bio: "Fashion axe food truck banh mi, tote bag meh dreamcatcher listicle gochujang lomo heirloom farm-to-table swag cray. +1 fap taxidermy, heirloom marfa ennui williamsburg green juice art party fingerstache paleo sustainable crucifix. Kogi yuccie bespoke cold-pressed, chia pork belly dreamcatcher pug. Asymmetrical fingerstache pabst, put a bird on it man braid pickled photo booth crucifix schlitz ethical cold-pressed forage pour-over. Small batch pinterest sartorial, chartreuse fanny pack four dollar toast artisan sriracha blue bottle chillwave viral stumptown yuccie crucifix tousled. Four dollar toast neutra hoodie, locavore raw denim fap drinking vinegar sriracha food truck disrupt dreamcatcher leggings. Yuccie skateboard locavore try-hard twee disrupt, selfies tousled kombucha dreamcatcher portland lo-fi.", admin: false, first_name: "Colton", last_name: "Thompsett", profile_picture: 46, password: "password"},
  {email: "percival_wash@gmail.com", encrypted_password: "$2a$11$AR9nAx3mBMNruJmd.F5IKOluii8QCIngo2BGpbt7n.9PqP9uMN.6u", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-06-22 19:07:01", last_sign_in_at: "2016-06-22 09:36:30", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "3719321829", location: "San Ramon, CA", bio: "Craft beer man bun bitters, lo-fi pitchfork health goth tote bag lumbersexual meh PBR&B authentic organic. Paleo kombucha iPhone tousled chia, green juice next level chillwave food truck four loko butcher. Irony tote bag photo booth drinking vinegar literally humblebrag. Kinfolk cold-pressed chillwave semiotics biodiesel paleo, fap put a bird on it pop-up before they sold out. Hella green juice thundercats leggings godard hammock. 3 wolf moon occupy YOLO, VHS waistcoat vegan mustache everyday carry direct trade health goth pickled kickstarter. Wayfarers fixie salvia art party tacos, pop-up migas pinterest mumblecore vinyl celiac.", admin: false, first_name: "Percival", last_name: "Wash", profile_picture: 63, password: "password"},
  {email: "gail_brewster@gmail.com", encrypted_password: "$2a$11$Z.YWJseD32.OBfIi5avrpufFEvMQKBgZrCIqMCf9UUH5n1A12EKie", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-06-22 21:22:55", last_sign_in_at: "2016-06-22 09:39:21", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "2781924728", location: "Alameda, CA", bio: "Kombucha four dollar toast deep v, tousled VHS vegan fap kitsch pug helvetica sartorial mlkshk raw denim tote bag. Mumblecore pitchfork cardigan sriracha. Cred cronut art party paleo street art, slow-carb DIY gochujang lumbersexual lo-fi bitters artisan viral etsy seitan. Distillery fap truffaut man bun, keytar viral sartorial. Heirloom quinoa +1 cardigan, tumblr pour-over iPhone asymmetrical. Swag freegan chillwave kitsch. Waistcoat kinfolk tousled man bun freegan tattooed.", admin: false, first_name: "Gail", last_name: "Brewster", profile_picture: 49, password: "password"},
  {email: "moss_pearce@hotmail.com", encrypted_password: "$2a$11$plvmmD.Bv.YrlmxNoqjFMOHSbOidcTz7SGPW98yHdMLC.c75iWCEW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-06-22 21:25:42", last_sign_in_at: "2016-06-22 21:18:47", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "3819220183", location: "San Ramon, CA", bio: "Tilde wolf hoodie, pickled kickstarter yuccie microdosing kitsch typewriter. Cold-pressed plaid street art heirloom readymade. Hashtag chartreuse venmo, vice quinoa tattooed ennui street art disrupt asymmetrical dreamcatcher cray taxidermy meditation. Brooklyn master cleanse tote bag, williamsburg ramps 90's distillery truffaut shoreditch squid hella. Godard etsy keffiyeh irony fixie, fanny pack flannel brooklyn cred wayfarers viral. Pop-up art party blue bottle, pug 8-bit schlitz beard. Intelligentsia waistcoat photo booth schlitz, green juice tattooed church-key keffiyeh lo-fi kale chips roof party small batch mlkshk kickstarter cold-pressed.", admin: false, first_name: "Moss", last_name: "Pearce", profile_picture: 50, password: "password"},
  {email: "ainslee_wootton@gmail.com", encrypted_password: "$2a$11$TrBuTSLxERTUX1lN3VVSsuB0VMFZGD88ViFu27n9.aPMcjMXlMjyO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-06-22 19:18:59", last_sign_in_at: "2016-06-22 19:08:25", current_sign_in_ip: "::1", last_sign_in_ip: "::1", phone_number: "8382012732", location: "San Leandro, CA", bio: "Messenger bag roof party pickled brooklyn, fingerstache kogi twee knausgaard mlkshk schlitz church-key. Brooklyn normcore freegan banjo four dollar toast viral, lumbersexual forage gentrify food truck hashtag intelligentsia blue bottle poutine. You probably haven't heard of them disrupt dreamcatcher, paleo single-origin coffee brunch kogi jean shorts flannel master cleanse XOXO leggings four dollar toast celiac. Lomo brunch trust fund irony, authentic scenester freegan hella echo park neutra organic. Cold-pressed swag shabby chic meh. Mixtape green juice cronut crucifix. Offal jean shorts vinyl seitan.", admin: false, first_name: "Ainslee", last_name: "Wootton", profile_picture: 66, password: "password"}
])
CategorizedBoardgame.create!([
  {category_id: 2, boardgame_id: 2},
  {category_id: 4, boardgame_id: 2},
  {category_id: 5, boardgame_id: 2},
  {category_id: 6, boardgame_id: 2},
  {category_id: 7, boardgame_id: 2},
  {category_id: 2, boardgame_id: 4},
  {category_id: 11, boardgame_id: 4},
  {category_id: 8, boardgame_id: 4},
  {category_id: 12, boardgame_id: 4},
  {category_id: 13, boardgame_id: 4},
  {category_id: 7, boardgame_id: 4},
  {category_id: 6, boardgame_id: 5},
  {category_id: 14, boardgame_id: 5},
  {category_id: 8, boardgame_id: 5},
  {category_id: 15, boardgame_id: 6},
  {category_id: 16, boardgame_id: 6},
  {category_id: 17, boardgame_id: 6},
  {category_id: 4, boardgame_id: 7},
  {category_id: 18, boardgame_id: 7},
  {category_id: 8, boardgame_id: 8},
  {category_id: 19, boardgame_id: 8},
  {category_id: 6, boardgame_id: 9},
  {category_id: 13, boardgame_id: 9},
  {category_id: 10, boardgame_id: 3},
  {category_id: 9, boardgame_id: 3},
  {category_id: 6, boardgame_id: 3},
  {category_id: 8, boardgame_id: 3},
  {category_id: 20, boardgame_id: 10},
  {category_id: 11, boardgame_id: 10},
  {category_id: 21, boardgame_id: 10},
  {category_id: 7, boardgame_id: 10},
  {category_id: 8, boardgame_id: 10},
  {category_id: 7, boardgame_id: 11},
  {category_id: 23, boardgame_id: 11},
  {category_id: 22, boardgame_id: 11},
  {category_id: 8, boardgame_id: 11},
  {category_id: 15, boardgame_id: 11},
  {category_id: 72, boardgame_id: 66},
  {category_id: 71, boardgame_id: 66},
  {category_id: 79, boardgame_id: 6},
  {category_id: 79, boardgame_id: 87},
  {category_id: 21, boardgame_id: 67},
  {category_id: 13, boardgame_id: 67},
  {category_id: 18, boardgame_id: 67},
  {category_id: 9, boardgame_id: 68},
  {category_id: 21, boardgame_id: 88},
  {category_id: 8, boardgame_id: 69},
  {category_id: 73, boardgame_id: 69},
  {category_id: 73, boardgame_id: 70},
  {category_id: 19, boardgame_id: 70},
  {category_id: 8, boardgame_id: 71},
  {category_id: 16, boardgame_id: 71},
  {category_id: 71, boardgame_id: 71},
  {category_id: 7, boardgame_id: 71},
  {category_id: 6, boardgame_id: 45},
  {category_id: 8, boardgame_id: 45},
  {category_id: 21, boardgame_id: 45},
  {category_id: 23, boardgame_id: 45},
  {category_id: 9, boardgame_id: 46},
  {category_id: 13, boardgame_id: 46},
  {category_id: 21, boardgame_id: 46},
  {category_id: 4, boardgame_id: 72},
  {category_id: 21, boardgame_id: 72},
  {category_id: 22, boardgame_id: 72},
  {category_id: 18, boardgame_id: 72},
  {category_id: 7, boardgame_id: 72},
  {category_id: 75, boardgame_id: 72},
  {category_id: 76, boardgame_id: 72},
  {category_id: 9, boardgame_id: 73},
  {category_id: 6, boardgame_id: 74},
  {category_id: 11, boardgame_id: 74},
  {category_id: 14, boardgame_id: 74},
  {category_id: 21, boardgame_id: 74},
  {category_id: 75, boardgame_id: 74},
  {category_id: 8, boardgame_id: 74},
  {category_id: 76, boardgame_id: 74},
  {category_id: 18, boardgame_id: 74},
  {category_id: 71, boardgame_id: 74},
  {category_id: 7, boardgame_id: 74},
  {category_id: 6, boardgame_id: 75},
  {category_id: 13, boardgame_id: 75},
  {category_id: 16, boardgame_id: 75},
  {category_id: 7, boardgame_id: 75},
  {category_id: 6, boardgame_id: 76},
  {category_id: 14, boardgame_id: 76},
  {category_id: 8, boardgame_id: 76},
  {category_id: 12, boardgame_id: 76},
  {category_id: 21, boardgame_id: 77},
  {category_id: 13, boardgame_id: 77},
  {category_id: 9, boardgame_id: 77},
  {category_id: 6, boardgame_id: 78},
  {category_id: 18, boardgame_id: 78},
  {category_id: 6, boardgame_id: 79},
  {category_id: 13, boardgame_id: 79},
  {category_id: 18, boardgame_id: 79},
  {category_id: 77, boardgame_id: 79},
  {category_id: 2, boardgame_id: 80},
  {category_id: 21, boardgame_id: 80},
  {category_id: 76, boardgame_id: 80},
  {category_id: 71, boardgame_id: 80},
  {category_id: 7, boardgame_id: 80},
  {category_id: 17, boardgame_id: 80},
  {category_id: 78, boardgame_id: 80},
  {category_id: 20, boardgame_id: 81},
  {category_id: 6, boardgame_id: 81},
  {category_id: 8, boardgame_id: 81},
  {category_id: 13, boardgame_id: 81},
  {category_id: 6, boardgame_id: 82},
  {category_id: 8, boardgame_id: 82},
  {category_id: 73, boardgame_id: 82},
  {category_id: 13, boardgame_id: 82},
  {category_id: 2, boardgame_id: 83},
  {category_id: 4, boardgame_id: 83},
  {category_id: 12, boardgame_id: 83},
  {category_id: 73, boardgame_id: 83},
  {category_id: 6, boardgame_id: 84},
  {category_id: 13, boardgame_id: 84},
  {category_id: 76, boardgame_id: 85},
  {category_id: 77, boardgame_id: 85},
  {category_id: 13, boardgame_id: 85},
  {category_id: 18, boardgame_id: 85},
  {category_id: 9, boardgame_id: 85},
  {category_id: 4, boardgame_id: 86},
  {category_id: 6, boardgame_id: 86},
  {category_id: 21, boardgame_id: 86},
  {category_id: 9, boardgame_id: 86},
  {category_id: 8, boardgame_id: 87},
  {category_id: 22, boardgame_id: 87},
  {category_id: 18, boardgame_id: 88},
  {category_id: 6, boardgame_id: 89},
  {category_id: 18, boardgame_id: 89},
  {category_id: 80, boardgame_id: 89},
  {category_id: 21, boardgame_id: 90},
  {category_id: 75, boardgame_id: 90},
  {category_id: 76, boardgame_id: 90},
  {category_id: 81, boardgame_id: 90},
  {category_id: 6, boardgame_id: 91},
  {category_id: 14, boardgame_id: 91},
  {category_id: 8, boardgame_id: 91},
  {category_id: 9, boardgame_id: 91},
  {category_id: 8, boardgame_id: 92},
  {category_id: 13, boardgame_id: 92},
  {category_id: 71, boardgame_id: 92},
  {category_id: 20, boardgame_id: 93},
  {category_id: 4, boardgame_id: 93},
  {category_id: 6, boardgame_id: 93},
  {category_id: 14, boardgame_id: 93},
  {category_id: 8, boardgame_id: 93},
  {category_id: 16, boardgame_id: 93},
  {category_id: 7, boardgame_id: 93},
  {category_id: 9, boardgame_id: 93},
  {category_id: 82, boardgame_id: 93},
  {category_id: 21, boardgame_id: 94},
  {category_id: 8, boardgame_id: 94},
  {category_id: 76, boardgame_id: 94},
  {category_id: 73, boardgame_id: 94},
  {category_id: 78, boardgame_id: 94},
  {category_id: 21, boardgame_id: 95},
  {category_id: 8, boardgame_id: 95},
  {category_id: 8, boardgame_id: 96},
  {category_id: 22, boardgame_id: 96},
  {category_id: 18, boardgame_id: 96},
  {category_id: 7, boardgame_id: 96},
  {category_id: 6, boardgame_id: 97},
  {category_id: 8, boardgame_id: 97},
  {category_id: 13, boardgame_id: 97}
])
Boardgame.create!([
  {name: "Agricola", developer: "Uwe Rosenberg"},
  {name: "Pandemic", developer: "Matt Leacock"},
  {name: "Dominion", developer: "Donald X. Vaccarino"},
  {name: "Carcassonne", developer: "Klaus-Jürgen Wrede"},
  {name: "For Sale", developer: "Stefan Dorra"},
  {name: "Saint Petersburg", developer: "Bernd Brunnhofer"},
  {name: "BANG!", developer: "Emiliano Sciarra"},
  {name: "Blood Rage", developer: "Eric Lang"},
  {name: "The Resistance", developer: "Don Eskridge"},
  {name: "Space Hulk: Death Angel", developer: "Corey Konieczka"},
  {name: "Puerto Rico", developer: "Andreas Seyfarth"},
  {name: "The Castles of Burgundy", developer: "Stefan Feld"},
  {name: "Le Havre", developer: "Uwe Rosenberg"},
  {name: "Brass", developer: "Martin Wallace"},
  {name: "Power Grid", developer: "Friedemann Friese"},
  {name: "Race for the Galaxy", developer: "Thomas Lehmann"},
  {name: "Eclipse", developer: "Touko Tahkokallio"},
  {name: "Caylus", developer: "William Attia"},
  {name: "Mage Knight", developer: "Vlaada Chvátil"},
  {name: "7 Wonders", developer: "Antoine Bauza"},
  {name: "Concordia", developer: "Mac Gerdts"},
  {name: "Stone Age", developer: "Bernd Brunnhofer"},
  {name: "Suburbia", developer: "Ted Alspach"},
  {name: "Castles of Mad King Ludwig", developer: "Ted Alspach"},
  {name: "Twilight Imperium", developer: "Christian T. Petersen"},
  {name: "Trajan", developer: "Stefan Feld"},
  {name: "Ticket to Ride", developer: "Alan R. Moon"},
  {name: "Hansa Teutonica", developer: "Andreas Steding"},
  {name: "Splendor", developer: "Marc André"},
  {name: "Ora et Labora", developer: "Uwe Rosenberg"},
  {name: "Alien Frontiers", developer: "Tory Niemann"},
  {name: "Love Letter", developer: "Seiji Kanai"},
  {name: "Galaxy Trucker", developer: "Vlaada Chvátil"},
  {name: "Patchwork", developer: "Uwe Rosenberg"},
  {name: "Istanbul", developer: "Rüdiger Dorn"},
  {name: "Lewis & Clark", developer: "Cédrick Chaboussit"},
  {name: "San Juan", developer: "Andreas Seyfarth"},
  {name: "Mombasa", developer: "Alexander Pfister"},
  {name: "The Settlers of Catan", developer: "Klaus Teuber"},
  {name: "Bruges", developer: "Stefan Feld"},
  {name: "Neuroshima Hex!", developer: "Michał Oracz"},
  {name: "Jaipur", developer: "Sébastien Pauchon"},
  {name: "Seasons", developer: "Régis Bonnessée"},
  {name: "Bora Bora", developer: "Stefan Feld"}
])

Category.create!([
  {mechanism: "Area control"},
  {mechanism: "Area movement"},
  {mechanism: "Card drafting"},
  {mechanism: "Variable player powers"},
  {mechanism: "Hand management"},
  {mechanism: "Worker placement"},
  {mechanism: "Area enclosure"},
  {mechanism: "Co-operative play"},
  {mechanism: "Point to point movement"},
  {mechanism: "Set collection"},
  {mechanism: "Deck building"},
  {mechanism: "Partnerships"},
  {mechanism: "Simultaneous action selection"},
  {mechanism: "Voting"},
  {mechanism: "Tile placement"},
  {mechanism: "Dice rolling"},
  {mechanism: "Player elimination"},
  {mechanism: "Take that"},
  {mechanism: "Action point allowance system"},
  {mechanism: "Action / Movement programming"},
  {mechanism: "Variable phase order"},
  {mechanism: "Tableau building"},
  {mechanism: "Route / Network building"},
  {mechanism: "Auction / Bidding"},
  {mechanism: "Grid movement"},
  {mechanism: "Modular board"},
  {mechanism: "Pattern building"},
  {mechanism: "Trading"},
  {mechanism: "Bluffing"},
  {mechanism: "Time track"},
  {mechanism: "Pick-up and deliver"},
  {mechanism: "Stock holding"}
])
Follow.create!([
  {follower_id: 2, followee_id: 33},
  {follower_id: 2, followee_id: 28},
  {follower_id: 2, followee_id: 29},
  {follower_id: 32, followee_id: 39},
  {follower_id: 32, followee_id: 42},
  {follower_id: 32, followee_id: 31},
  {follower_id: 32, followee_id: 40},
  {follower_id: 35, followee_id: 32},
  {follower_id: 35, followee_id: 37},
  {follower_id: 35, followee_id: 31},
  {follower_id: 35, followee_id: 34},
  {follower_id: 35, followee_id: 39},
  {follower_id: 35, followee_id: 29},
  {follower_id: 36, followee_id: 34},
  {follower_id: 36, followee_id: 32},
  {follower_id: 36, followee_id: 37},
  {follower_id: 36, followee_id: 33},
  {follower_id: 36, followee_id: 38},
  {follower_id: 39, followee_id: 42},
  {follower_id: 39, followee_id: 35},
  {follower_id: 39, followee_id: 33},
  {follower_id: 39, followee_id: 36},
  {follower_id: 39, followee_id: 2},
  {follower_id: 39, followee_id: 34},
  {follower_id: 42, followee_id: 28},
  {follower_id: 42, followee_id: 29},
  {follower_id: 42, followee_id: 32},
  {follower_id: 31, followee_id: 2},
  {follower_id: 31, followee_id: 33},
  {follower_id: 31, followee_id: 29},
  {follower_id: 31, followee_id: 39},
  {follower_id: 33, followee_id: 36},
  {follower_id: 33, followee_id: 29},
  {follower_id: 33, followee_id: 28},
  {follower_id: 33, followee_id: 30},
  {follower_id: 33, followee_id: 40},
  {follower_id: 33, followee_id: 31},
  {follower_id: 33, followee_id: 39},
  {follower_id: 41, followee_id: 34},
  {follower_id: 41, followee_id: 42},
  {follower_id: 41, followee_id: 2},
  {follower_id: 41, followee_id: 33},
  {follower_id: 41, followee_id: 38},
  {follower_id: 40, followee_id: 31},
  {follower_id: 40, followee_id: 35},
  {follower_id: 40, followee_id: 38},
  {follower_id: 40, followee_id: 32},
  {follower_id: 40, followee_id: 34},
  {follower_id: 40, followee_id: 39},
  {follower_id: 40, followee_id: 30},
  {follower_id: 2, followee_id: 32},
  {follower_id: 2, followee_id: 31},
  {follower_id: 2, followee_id: 37},
  {follower_id: 2, followee_id: 38},
  {follower_id: 2, followee_id: 34},
  {follower_id: 2, followee_id: 41},
  {follower_id: 2, followee_id: 35},
  {follower_id: 2, followee_id: 42}
])
Ownership.create!([
  {user_id: 2, boardgame_id: 6, rating: 9, num_of_plays: 12},
  {user_id: 39, boardgame_id: 73, rating: 7, num_of_plays: 5},
  {user_id: 39, boardgame_id: 78, rating: 6, num_of_plays: 4},
  {user_id: 2, boardgame_id: 10, rating: 8, num_of_plays: 3},
  {user_id: 39, boardgame_id: 46, rating: 7, num_of_plays: 8},
  {user_id: 39, boardgame_id: 74, rating: 8, num_of_plays: 1},
  {user_id: 40, boardgame_id: 83, rating: 8, num_of_plays: 2},
  {user_id: 40, boardgame_id: 9, rating: 7, num_of_plays: 4},
  {user_id: 40, boardgame_id: 68, rating: 9, num_of_plays: 5},
  {user_id: 2, boardgame_id: 2, rating: 10, num_of_plays: 8},
  {user_id: 2, boardgame_id: 85, rating: 8, num_of_plays: 1},
  {user_id: 28, boardgame_id: 73, rating: 5, num_of_plays: 1},
  {user_id: 28, boardgame_id: 92, rating: 9, num_of_plays: 12},
  {user_id: 28, boardgame_id: 89, rating: 8, num_of_plays: 20},
  {user_id: 28, boardgame_id: 6, rating: 7, num_of_plays: 8},
  {user_id: 29, boardgame_id: 70, rating: 7, num_of_plays: 3},
  {user_id: 29, boardgame_id: 9, rating: 8, num_of_plays: 5},
  {user_id: 29, boardgame_id: 69, rating: 8, num_of_plays: 2},
  {user_id: 29, boardgame_id: 94, rating: 7, num_of_plays: 25},
  {user_id: 29, boardgame_id: 8, rating: 7, num_of_plays: 8},
  {user_id: 29, boardgame_id: 93, rating: 9, num_of_plays: 6},
  {user_id: 29, boardgame_id: 86, rating: 8, num_of_plays: 4},
  {user_id: 29, boardgame_id: 91, rating: 8, num_of_plays: 3},
  {user_id: 29, boardgame_id: 84, rating: 6, num_of_plays: 15},
  {user_id: 29, boardgame_id: 71, rating: 8, num_of_plays: 4},
  {user_id: 30, boardgame_id: 75, rating: 8, num_of_plays: 9},
  {user_id: 30, boardgame_id: 80, rating: 10, num_of_plays: 3},
  {user_id: 30, boardgame_id: 46, rating: 7, num_of_plays: 6},
  {user_id: 30, boardgame_id: 4, rating: 8, num_of_plays: 5},
  {user_id: 31, boardgame_id: 46, rating: 8, num_of_plays: 2},
  {user_id: 31, boardgame_id: 91, rating: 9, num_of_plays: 4},
  {user_id: 31, boardgame_id: 90, rating: 6, num_of_plays: 2},
  {user_id: 31, boardgame_id: 67, rating: 5, num_of_plays: 7},
  {user_id: 32, boardgame_id: 3, rating: 10, num_of_plays: 3},
  {user_id: 32, boardgame_id: 45, rating: 8, num_of_plays: 2},
  {user_id: 32, boardgame_id: 66, rating: 8, num_of_plays: 5},
  {user_id: 32, boardgame_id: 11, rating: 4, num_of_plays: 7},
  {user_id: 32, boardgame_id: 85, rating: 7, num_of_plays: 1},
  {user_id: 32, boardgame_id: 9, rating: 6, num_of_plays: 3},
  {user_id: 32, boardgame_id: 73, rating: 8, num_of_plays: 10},
  {user_id: 32, boardgame_id: 68, rating: 8, num_of_plays: 16},
  {user_id: 32, boardgame_id: 81, rating: 8, num_of_plays: 4},
  {user_id: 32, boardgame_id: 78, rating: 6, num_of_plays: 6},
  {user_id: 33, boardgame_id: 7, rating: 7, num_of_plays: 5},
  {user_id: 33, boardgame_id: 5, rating: 8, num_of_plays: 8},
  {user_id: 33, boardgame_id: 97, rating: 9, num_of_plays: 3},
  {user_id: 34, boardgame_id: 87, rating: 6, num_of_plays: 8},
  {user_id: 34, boardgame_id: 77, rating: 7, num_of_plays: 3},
  {user_id: 34, boardgame_id: 88, rating: 8, num_of_plays: 5},
  {user_id: 34, boardgame_id: 91, rating: 10, num_of_plays: 2},
  {user_id: 35, boardgame_id: 74, rating: 10, num_of_plays: 6},
  {user_id: 35, boardgame_id: 69, rating: 7, num_of_plays: 3},
  {user_id: 35, boardgame_id: 93, rating: 8, num_of_plays: 2},
  {user_id: 35, boardgame_id: 72, rating: 8, num_of_plays: 12},
  {user_id: 35, boardgame_id: 76, rating: 6, num_of_plays: 1},
  {user_id: 35, boardgame_id: 68, rating: 7, num_of_plays: 7},
  {user_id: 35, boardgame_id: 5, rating: 7, num_of_plays: 5},
  {user_id: 35, boardgame_id: 70, rating: 7, num_of_plays: 2},
  {user_id: 35, boardgame_id: 46, rating: 8, num_of_plays: 3},
  {user_id: 35, boardgame_id: 79, rating: 5, num_of_plays: 2},
  {user_id: 35, boardgame_id: 85, rating: 8, num_of_plays: 5},
  {user_id: 36, boardgame_id: 68, rating: 8, num_of_plays: 2},
  {user_id: 36, boardgame_id: 3, rating: 9, num_of_plays: 6},
  {user_id: 36, boardgame_id: 70, rating: 7, num_of_plays: 3},
  {user_id: 36, boardgame_id: 71, rating: 8, num_of_plays: 8},
  {user_id: 36, boardgame_id: 76, rating: 8, num_of_plays: 2},
  {user_id: 36, boardgame_id: 4, rating: 6, num_of_plays: 10},
  {user_id: 36, boardgame_id: 75, rating: 7, num_of_plays: 6},
  {user_id: 36, boardgame_id: 74, rating: 7, num_of_plays: 1},
  {user_id: 36, boardgame_id: 8, rating: 7, num_of_plays: 12},
  {user_id: 36, boardgame_id: 87, rating: 7, num_of_plays: 15},
  {user_id: 36, boardgame_id: 91, rating: 9, num_of_plays: 3},
  {user_id: 37, boardgame_id: 96, rating: 7, num_of_plays: 8},
  {user_id: 37, boardgame_id: 90, rating: 6, num_of_plays: 2},
  {user_id: 37, boardgame_id: 71, rating: 9, num_of_plays: 5},
  {user_id: 38, boardgame_id: 2, rating: 8, num_of_plays: 3},
  {user_id: 38, boardgame_id: 10, rating: 7, num_of_plays: 8},
  {user_id: 38, boardgame_id: 85, rating: 10, num_of_plays: 4},
  {user_id: 38, boardgame_id: 77, rating: 9, num_of_plays: 3},
  {user_id: 39, boardgame_id: 86, rating: 7, num_of_plays: 3},
  {user_id: 39, boardgame_id: 96, rating: 7, num_of_plays: 7},
  {user_id: 39, boardgame_id: 76, rating: 8, num_of_plays: 8},
  {user_id: 39, boardgame_id: 93, rating: 9, num_of_plays: 2},
  {user_id: 39, boardgame_id: 70, rating: 6, num_of_plays: 4},
  {user_id: 39, boardgame_id: 8, rating: 7, num_of_plays: 12},
  {user_id: 39, boardgame_id: 95, rating: 8, num_of_plays: 2},
  {user_id: 41, boardgame_id: 75, rating: 7, num_of_plays: 3},
  {user_id: 41, boardgame_id: 72, rating: 9, num_of_plays: 2},
  {user_id: 41, boardgame_id: 92, rating: 8, num_of_plays: 5},
  {user_id: 41, boardgame_id: 74, rating: 9, num_of_plays: 1},
  {user_id: 41, boardgame_id: 87, rating: 5, num_of_plays: 2},
  {user_id: 42, boardgame_id: 73, rating: 8, num_of_plays: 4},
  {user_id: 42, boardgame_id: 76, rating: 7, num_of_plays: 2},
  {user_id: 42, boardgame_id: 66, rating: 9, num_of_plays: 5},
  {user_id: 33, boardgame_id: 74, rating: 10, num_of_plays: 4},
  {user_id: 33, boardgame_id: 96, rating: 3, num_of_plays: 6},
  {user_id: 2, boardgame_id: 8, rating: 8, num_of_plays: 15},
  {user_id: 2, boardgame_id: 88, rating: 8, num_of_plays: 3},
  {user_id: 2, boardgame_id: 75, rating: 8, num_of_plays: 6}
])
Picture.create!([
  {user_id: 2, link: "https://s-media-cache-ak0.pinimg.com/736x/7f/38/83/7f388315dd991c282119b0c6608682ab.jpg"},
  {user_id: 28, link: "https://assets.entrepreneur.com/content/16x9/822/20150406145944-dos-donts-taking-perfect-linkedin-profile-picture-selfie-mobile-camera-2.jpeg"},
  {user_id: 28, link: "http://i.imgur.com/vvxuF7g.jpg"},
  {user_id: 29, link: "http://www.google.com/+/images/learnmore/hero/hero-profile.jpg"},
  {user_id: 30, link: "https://lh3.googleusercontent.com/-wysvRmf4xz4/AAAAAAAAAAI/AAAAAAAAAAA/GluI72KIjv0/photo.jpg"},
  {user_id: 31, link: "https://organicthemes.com/demo/profile/files/2012/12/profile_img.png"},
  {user_id: 31, link: "http://www.analoggames.com/wp-content/uploads/2016/01/board_game_shelf_analog_card_games_03.jpg"},
  {user_id: 32, link: "https://s-media-cache-ak0.pinimg.com/236x/af/d0/74/afd074b73d5d3005300e87dd4ccecdbf.jpg"},
  {user_id: 33, link: "https://s3.amazonaws.com/37assets/svn/1065-IMG_2529.jpg"},
  {user_id: 34, link: "https://upload.wikimedia.org/wikipedia/commons/6/65/Kruse_CNDLS_Profile.png"},
  {user_id: 35, link: "http://www.hideoconcert.com/blog/wp-content/uploads/2013/03/P1020094-optimized_for_web.jpg"},
  {user_id: 36, link: "https://sodaklady.files.wordpress.com/2007/04/game-shelf-2007.jpg"},
  {user_id: 37, link: "http://sms.latestsms.in/wp-content/uploads/facebook-profile-pictures43.jpg"},
  {user_id: 38, link: "https://pbs.twimg.com/profile_images/1731485432/justin-profile-face.jpg"},
  {user_id: 39, link: "https://boardgametime.files.wordpress.com/2012/04/board_game_collection22.jpg"},
  {user_id: 40, link: "http://img05.deviantart.net/038e/i/2010/150/b/0/me_2010_by_axy_stock.jpg"},
  {user_id: 41, link: "http://img08.deviantart.net/9d6c/i/2012/253/4/d/2012_id_by_density_stock-d5e8sph.jpg"},
  {user_id: 32, link: "http://www.illumni.co/wp-content/uploads/2014/06/No.-1.jpg"},
  {user_id: 2, link: "http://static.eharmony.com/blog/wp-content/uploads/2010/04/eHarmony-Blog-profile-picture.jpg"},
  {user_id: 35, link: "http://www.doutua.com/Public/UserPic/default.jpg"},
  {user_id: 36, link: "https://s-media-cache-ak0.pinimg.com/736x/99/0a/7b/990a7b0c2cf2fdaf93385194e722d802.jpg"},
  {user_id: 39, link: "https://media.licdn.com/mpr/mpr/p/8/005/08f/04e/213380f.jpg"},
  {user_id: 42, link: "http://style.pk/wp-content/uploads/2015/08/Pakistani-Actress-Anum-Fayyaz-Profile-And-Pictures0012.jpg"}
])
